services:
  db:
    image: pgvector/pgvector:pg16 # <--- ¡La imagen mágica con vector incluido!
    container_name: uagrm_bot_db
    restart: always
    environment:
      - POSTGRES_DB=uagrm_bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
